### PR TITLE
Enable chunked response

### PR DESCRIPTION
**Pull request by marcoow**
This enabled chunked response via a config option. It is not ready to be merged as it depends on ember-fastboot/fastboot#176

### CODE REVIEW

**Comment by marcoow** [comment]
@kratiahuja, @rwjblue: do you have a minute to review?

**Comment by marcoow** [comment]
@kratiahuja: now that response chunks are released in fastboot this should be good to merge as well? Once this is in, I'll submit a PR for fastboot-app-server to make that forward the option to the middleware so response chunks are conveniently usable.

**Comment by kratiahuja** [comment]
@marcoow yes, sorry I missed seeing this PR.

**Comment by kratiahuja** [comment]
v1.1.1 is published.

**Comment by marcoow** [comment]
Thanks @kratiahuja!

**Comment by marcoow** [comment]
@kratiahuja: see ember-fastboot/fastboot-app-server#68 for the last PR exposing this in fastboot-app-server for easy consumption

**Pull request merged**
